### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by rhedwan** [zuri-training/my_cms-team18#28]
@christianahsasona @codelikesuraj @EmmanuelHillary @Blackburn0  kindly fix this error on your local server

<img width="1440" alt="Screenshot 2022-08-12 at 11 55 45 PM" src="https://user-images.githubusercontent.com/48237269/184454568-a5a21c75-d701-48be-a97e-b810982fa6cc.png">

**Comment by EmmanuelHillary** [comment]
> @christianahsasona @codelikesuraj @EmmanuelHillary @Blackburn0  kindly fix this error on your local server
> 
> <img width="1440" alt="Screenshot 2022-08-12 at 11 55 45 PM" src="https://user-images.githubusercontent.com/48237269/184454568-a5a21c75-d701-48be-a97e-b810982fa6cc.png"> 
> 
> 
> 

Alright, running "pip install tkinter" or "sudo apt-get install python3-tk" on Linux terminal should fix it

**Comment by rhedwan** [comment]
@EmmanuelHillary the problem is not the installation. The issue is 'tkinter' was mistakenly used on the project.

**Comment by Blackburn0** [comment]
@rhedwan  please check again we have updated our code on GitHub
So you can pull for the latest update
Then if it doesn't work please kindly suggest a possible solution
Thanks

**Comment by rhedwan** [comment]
https://forge.zurifordummies.com/
@christianahsasona @codelikesuraj  @EmmanuelHillary  @Blackburn0

**Comment by Blackburn0** [comment]
@rhedwan thanks
We appreciate your help ☺️

**Comment by Blackburn0** [comment]
@rhedwan Good morning sir
Please we have made some changes to our repo 
Please could you help us redeploy it 🙏🙏
We would really appreciate it
